### ISSUE TITLE
sha256 (and sha***) is documented but not supported

### ISSUE THREAD

**Issue by petitout** [go-playground/validator#944] opened 2022-05-13 14:12 UTC
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 
v10

### Issue, Question or Enhancement:
sha256 (and sha***) is documented but not supported

### Code sample, to showcase or reproduce:

```go
type MyStruct struct {
	Hash string `validate:"sha256"`
}

```

fails with
```
Undefined validation function 'sha256' on field 'Hash'
```

**Comment by sdillen** [comment] 2022-05-24 08:14
Most of this hash validations where just added a couple of days ago (see https://github.com/go-playground/validator/pull/875). You need to make sure that you point to the latest version of this package in your `go.mod`.

It will be most likely something like this:
```diff
+ require github.com/go-playground/validator/v10 v10.11.0
- require github.com/go-playground/validator/v10 v10.10.0
```

**Comment by jmvbxx** [comment] 2022-12-02 13:12
I am not able to reproduce the above error using the most up-to-date version. Is this issue good to close?

**Comment by zemzale** [comment] 2022-12-27 14:11
Closing this as not reproducible.

**Closed by zemzale** 2022-12-27 14:11 UTC
