### ISSUE TITLE
How to verify oneOf constraint

### ISSUE THREAD

**Issue by vitali108** [go-playground/validator#500] opened 2019-08-08 15:10 UTC
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
I have the following struct where either Zone OR Target must be present. If Target is present, then either Href OR Id must be present. If Zone is present, then either Href or Name must be present. I have encoded validation as follows:
```golang
type Template struct {
	Name          string `json:"name" validate:"min=1,max=63"`
	Target* Target `json:"target" validate:"required_without=Zone,dive"`
	Zone*   Zone `json:"zone" validate:"required_without=Target,dive"`
}

type Target struct {
	Href string `json:"href" validate:"required_without=Id,omitempty"`
	Id   string `json:"id" validate:"required_without=Href,omitempty,min=1,max=64"`
}

type Zone struct {
	Href string `json:"href" validate:"required_without=Name"`
	Name string `json:"name" validate:"required_without=Href,min=1,max=63"`
}
```
When I run validation on the following example:
```json
{
    "name": "d",
    "zone": {
        "name": "x"
    }
}
```
I get the following failure `FieldName:'Template.Target'  ValidateTag:'required_without'  ActualData:'<nil>'`

Why does `required_without` fire on Target being `nil` if `Zone` is present? 
Is there better way to verify my constraints?

   Thank you, 
         Vitali

**Comment by deankarn** [comment] 2019-08-24 16:45
@vitali108 thanks for the issue,

I think that `required_without` isn't handling struct properly is the crux of the problem. I won't be able to take a look at this for a bit, but have marked it with `help wanted` so that the community can help out :)

**Comment by leafduo** [comment] 2019-09-22 19:39
I think this is a duplicate of https://github.com/go-playground/validator/issues/483

**Comment by deankarn** [comment] 2019-09-29 22:26
closing as duplicate.

**Closed by deankarn** 2019-09-29 22:26 UTC
Labels: bug, duplicate, help wanted
